# -*- coding: utf-8 -*-
"""Data analysis part B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ixBxpJN3ziS2FXbe40cIdCWVDMbtB4ct
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset_path = 'C:\Users\Admin\AIO-189-phatpham-1\Module 3\Week 1\opsd_germany_daily.csv'
opsd_daily = pd.read_csv(dataset_path)

print(opsd_daily.shape)
print(opsd_daily.dtypes)
opsd_daily.head(3)

opsd_daily['Date'] = pd.to_datetime(opsd_daily['Date'])
opsd_daily = opsd_daily.set_index('Date')

opsd_daily['Year'] = opsd_daily.index.year
opsd_daily['Month'] = opsd_daily.index.month
opsd_daily['Weekday Name'] = opsd_daily.index.day_name()
opsd_daily.sample(5)

sns.set(rc={'figure.figsize':(11, 4)})
opsd_daily['Consumption'].plot(linewidth=0.5);
plt.show()

fig, axes = plt.subplots(3, 1, figsize=(22, 10), sharex=True)
for name, ax in zip(['Consumption', 'Solar', 'Wind'], axes):
    sns.boxplot(data=opsd_daily, x='Month', y=name, ax=ax)
    ax.set_ylabel('GWh')
    ax.set_title(name)
plt.show()

opsd_daily = opsd_daily.asfreq('D')
opsd_daily['Consumption - Forward Fill'] = opsd_daily['Consumption'].fillna(method='ffill')

opsd_daily[['Consumption', 'Consumption - Forward Fill']].head(10)

opsd_weekly_mean = opsd_daily[['Consumption', 'Wind', 'Solar', 'Wind+Solar']].resample('W').mean()

fig, ax = plt.subplots()
start, end = '2017-01', '2017-06'
ax.plot(opsd_daily.loc[start:end, 'Solar'], marker='.', linestyle='-', linewidth=0.5, label='Daily')
ax.plot(opsd_weekly_mean.loc[start:end, 'Solar'], marker='o', markersize=8, linestyle='-', label='Weekly Mean Resample')
ax.set_ylabel('Solar Production (GWh)')
ax.legend()
plt.show()

opsd_7d = opsd_daily[['Consumption', 'Wind', 'Solar', 'Wind+Solar']].rolling(7, center=True).mean()

opsd_7d.head(10)

opsd_365d = opsd_daily[['Consumption', 'Wind', 'Solar', 'Wind+Solar']].rolling(window=365, center=True).mean()

fig, ax = plt.subplots()
ax.plot(opsd_daily['Consumption'], marker='.', linestyle='-', linewidth=0.5, label='Daily')
ax.plot(opsd_7d['Consumption'], linewidth=2, label='7-d Rolling Mean')
ax.plot(opsd_365d['Consumption'], color='0.2', linewidth=3, label='Trend (365-d Rolling Mean)')
ax.legend()
ax.set_xlabel('Year')
ax.set_ylabel('Consumption (GWh)')
plt.show()